public class ObjectiveModel {
    public String id;
    public String conversationId;
    public String createdDate;
    public PersonModel creator;
    public String category;
    public String companyObjective;
    public String closedDate;
    public String description;
    public String endDate;
    public String priority;
    public String reviewDate;
    public String status;
    public String tmId;
    public String title;
    public String visibility;
    public TaskModel[] tasks;
    public ObjectiveCollaboratorModel[] collaborators;
}