public class HttpUtils {
    public static final Integer STATUS_OK = 200;
    public static final Integer STATUS_CREATED = 201;
    public static final Integer STATUS_BAD_REQUEST = 400;
    public static final Integer STATUS_FORBIDDEN = 403;
    public static final Integer STATUS_NOT_FOUND = 404;
    public static final Integer STATUS_METHOD_NOT_ALLOWED = 405;
    public static final Integer STATUS_CONFLICT = 409;
    public static final Integer STATUS_INTERNAL_SERVER_ERROR = 500;
}
